一口气发了很多个请求，一直在pendding中；尝试申请请求过多，也会造成卡顿

```
asynv send(chunks, limit = 4) {
  return new Promise((resolve, reject) => {
    const len = chunks.length
    let counter = 0
    let isStop = false
    
    const start = async () => {
      if (isStop) {
        return
      }
      const task = chunks.shift()
      if (task) {
        const { form, index } = task
        
        try {
          await http('xxx', form, {
            onUploadProgress: progress => {
              
            }
          })
          if (counter == len - 1) {
            resolve()
          } else {
            counter ++
            start()
          }
        } catch (e) {
          this.chunks[index].progress = -1
          if (task.error < 3) {
            task.error++
            chunks.unshift(task)
            start()
          } else {
            isStop = true
            reject()
          }
        }
      }
    }
    
    while(limit > 0) {
      start()
      limit -= 1
    }
  })
}
```

报错数量限制，通过try catch，代码在上面

